# Generated by Django 4.2.1 on 2023-08-09 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost_per_item', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ammount_in_stock', models.IntegerField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('ammount_sold', models.IntegerField(max_length=20)),
                ('sales_of_item', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('last_sales_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordername', models.CharField(max_length=100)),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('last_order_date', models.DateField(auto_now=True)),
                ('Orderer_Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.youritem')),
            ],
        ),
    ]
