# Generated by Django 4.2.1 on 2023-08-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_youritem_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youritem',
            name='ammount_in_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='youritem',
            name='ammount_sold',
            field=models.IntegerField(),
        ),
    ]
