# Generated by Django 4.2.1 on 2023-08-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_youritem_ammount_in_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youritem',
            name='location',
        ),
    ]
