# Generated by Django 4.2.1 on 2023-08-10 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordername', models.CharField(max_length=100)),
                ('order_location', models.CharField(max_length=100)),
                ('orderer_phoneno', models.IntegerField()),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('last_order_date', models.DateField(auto_now=True)),
                ('Orderer_Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.youritem')),
            ],
        ),
    ]
